import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Language': 'Language',
          'Select language': 'Select language',
          'Close': 'Close',
          'Edit Profile': 'Edit Profile',
          'Theme': 'Theme',
          'Terms': 'Terms',
          'Help Center': 'Help Center',
          'App language': 'App language',
          'Contact us': 'Contact us',
          'App info': 'App info',
          'Private Profile': 'Private Profile',
          'Enable': 'Enable',
          'Disable': 'Disable',
          'Update': 'Update',
          'Continue': 'Continue',
          'Settings': 'Settings',
          'Logout': 'Logout',
          'Location': 'Location',
          'About': 'About',
          'Interests': 'Interests',
          'Gallery': 'Gallery',
          'Read more': 'Read more',
          'Show less': 'Show less',
          'See all': 'See all',
          'Messages': 'Messages',
          'Activities': 'Activities',
          'Search': 'Search',
          'Select Activity': 'Select Activity',
          'Go-Live': 'Go-Live',
          'Stream Now': 'Stream Now',
          'Reels': 'Reels',
          'Add Reels': 'Add Reels',
          'Story': 'Story',
          'Publish Story': 'Publish Story',
          'Notification': 'Notification',
          'Matches': 'Matches',
          'Likes': 'Likes',
          'Visits': 'Visits',
          'Requests': 'Requests',
          'Permission': 'Permission',
          'Push Notifications': 'Push Notifications',
          'Your message': 'Your message',
          'View Profile': 'View Profile',
          'Block': 'Block',
          'Online': 'Online',
          'Premium': 'Premium',
          'Clear chat': 'Clear chat',
          'Algorithm': 'Algorithm',
          'Already have an account?': 'Already have an account?',
          'Create an account': 'Create an account',
          'Sign In': 'Sign In',
          'Sign up to continue': 'Sign up to continue',
          'Use phone number': 'Use phone number',
          'or sign up with': 'or sign up with',
          'Terms of use': 'Terms of use',
          'Privacy Policy': 'Privacy Policy',
          'My mobile': 'My mobile',
          'Please enter your valid phone number. We will send you a 4-digit code to verify your account.':
              'Please enter your valid phone number. We will send you a 4-digit code to verify your account.',
          'Enter your phone number': 'Enter your phone number',
          'Type the verification code we’ve sent you':
              'Type the verification code we’ve sent you',
          'send again': 'send again',
          'Skip': 'Skip',
          'Man': 'Man',
          'Women': 'Women',
          'Male': 'Male',
          'Female': 'Female',
          'Both': 'Both',
          'Search friend’s': 'Search friend’s',
          'Choose another': 'Choose another',
          'Choose birthday date': 'Choose birthday date',
          'First name': 'First name',
          'Enter first name': 'Enter first name',
          'Last name': 'Last name',
          'Enter last name': 'Enter last name',
          'Profile details': 'Profile details',
          'Your Passions': 'Your Passions',
          'You can find friends from your contact lists\nto connected':
              'You can find friends from your contact lists\nto connected',
          'Select a few of your interests and let everyone know what you’re passionate about.':
              'Select a few of your interests and let everyone know what you’re passionate about.',
          'Access to a contact list': 'Access to a contact list',
          'Enable notification’s': 'Enable notification’s',
          'Get push-notification when you get the match or receive a message.':
              'Get push-notification when you get the match or receive a message.',
          'I want to be notified': 'I want to be notified',
          'Discover': 'Discover',
          'Filters': 'Filters',
          'Distance': 'Distance',
          'Age': 'Age',
          'Today': 'Today',
          'Yesterday': 'Yesterday',
          'Sort by': 'Sort by',
          'Match Sort': 'Match Sort',
          'Name': 'Name',
          'Date & Time': 'Date & Time',
          'Ascending': 'Ascending',
          'Descending': 'Descending',
          'Confirm': 'Confirm',
          'This is a list of people who have liked you and your matches.':
              'This is a list of people who have liked you and your matches.',
          'Interested in': 'Interested in',
          'My Basics': 'My Basics',
          'My Work & Education': 'My Work & Education',
          'Height': 'Height',
          'Ethnicity': 'Ethnicity',
          'Religion': 'Religion',
          'Exercise': 'Exercise',
          'Smoking': 'Smoking',
          'Drinking': 'Drinking',
          'Kids': 'Kids',
          'Star sign': 'Star sign',
          'Core values': 'Core values',
          'Edit Basic Info': 'Edit Basic Info',
          'I am': 'I am',
          'My religion is': 'My religion is',
          'Hindu': 'Hindu',
          'Muslim': 'Muslim',
          'Sikh': 'Sikh',
          'Other': 'Other',
          'Jewish': 'Jewish',
          'Christian': 'Christian',
          'This is a list of people  who share a potential connection and a core connection':
              'This is a list of people  who share a potential connection and a core connection',
          'Select date of birth': 'Select date of birth',
          'My Deep Qualities': 'My Deep Qualities',
          "View Event":"View Event"

        },
        'hi_IN': {
          'Language': 'भाषा',
          'Select language': 'भाषा चुने',
          'Close': 'बंद करें',
          'Edit Profile': 'बंद करें',
          'Theme': 'थीम',
          'Terms': 'शर्तें',
          'Help Center': 'सहायता केंद्र',
          'App language': 'ऐप भाषा',
          'Contact us': 'संपर्क करें',
          'App info': 'अनुप्रयोग की जानकारी',
          'Private Profile': 'निजी प्रोफ़ाइल',
          'Enable': 'सक्षम',
          'Disable': 'अक्षम',
          'Update': 'अद्यतन',
          'Continue': 'जारी रखना',
          'Settings': 'समायोजन',
          'Logout': 'लॉग आउट',
          'Location': 'जगह',
          'About': 'बारे में',
          'Interests': 'रूचियाँ',
          'Gallery': 'गेलरी',
          'Read more': 'और पढ़ें',
          'Show less': 'कम दिखाएं',
          'See all': 'सभी देखें',
          'Messages': 'संदेशों',
          'Activities': 'गतिविधियाँ',
          'Search': 'खोज',
          'Select Activity': 'गतिविधि चुनें',
          'Go-Live': 'रहने जाओ',
          'Stream Now': 'अभी स्ट्रीम करें',
          'Reels': 'रीलें',
          'Add Reels': 'रीलें जोड़ें',
          'Story': 'कहानी',
          'Publish Story': 'कहानी प्रकाशित करें',
          'Notification': 'अधिसूचना',
          'Matches': 'मिलान',
          'Likes': 'पसंद',
          'Visits': 'दौरा',
          'Requests': 'अनुरोध',
          'Permission': 'अनुमति',
          'Push Notifications': 'पुश नोटीफिकेशन',
          'Your message': 'आपका संदेश',
          'View Profile': 'प्रोफ़ाइल देखें',
          'Block': 'अवरोध पैदा करना',
          'Clear chat': 'चैट हटाएं',
          'Online': 'ऑनलाइन',
          'Premium': 'अधिमूल्य',
          'Algorithm': 'कलन विधि',
          'Already have an account?': 'क्या आपके पास पहले से एक खाता मौजूद है?',
          'Create an account': 'खाता बनाएं',
          'Sign In': 'दाखिल करना',
          'Sign up to continue': 'जारी रखने के लिए साइन अप करें',
          'Continue with email': 'ईमेल जारी रखें',
          'Use phone number': 'फ़ोन नंबर का उपयोग करें',
          'or sign up with': 'या साइन अप करें',
          'Terms of use': 'उपयोग की शर्तें',
          'Privacy Policy': 'गोपनीयता नीति',
          'My mobile': 'मेरे मोबाइल',
          'Please enter your valid phone number. We will send you a 4-digit code to verify your account.':
              'कृपया अपना वैध फ़ोन नंबर दर्ज करें. हम आपके खाते को सत्यापित करने के लिए आपको 4 अंकों का कोड भेजेंगे।',
          'Enter your phone number': 'अपना फोन नंबर डालें',
          'Type the verification code we’ve sent you':
              'वह सत्यापन कोड टाइप करें जो हमने आपको भेजा है',
          'send again': 'पुनः भेजें',
          'Skip': 'छोडना',
          'Man': 'आदमी',
          'Women': 'औरत',
          'Male': 'नर',
          'Female': 'महिला',
          'Both': 'दोनों',
          'Search friend’s': 'मित्र खोजें',
          'Access to a contact list': 'संपर्क सूची तक पहुंच',
          'Choose another': 'दुसरे का चयन करें',
          'Choose birthday date': 'जन्मदिन की तारीख चुनें',
          'First name': 'पहला नाम',
          'Enter first name': 'प्रथम नाम दर्ज करें',
          'Last name': 'उपनाम',
          'Enter last name': 'अंतिम नाम दर्ज करो',
          'Profile details': 'प्रोफ़ाइल विवरण',
          'Your Passions': 'आपके जुनून',
          'You can find friends from your contact lists\nto connected':
              'आप अपनी संपर्क सूची \n से जुड़े हुए मित्रों को ढूंढ सकते हैं',
          'Select a few of your interests and let everyone know what you’re passionate about.':
              'अपनी कुछ रुचियों का चयन करें और सभी को बताएं कि आप किसमें रुचि रखते हैं।',
          'Enable notification’s': 'सूचनाएं सक्षम करें',
          'Get push-notification when you get the match or receive a message.':
              'जब आपको मैच मिले या कोई संदेश प्राप्त हो तो पुश-नोटिफिकेशन प्राप्त करें।',
          'I want to be notified': 'मैं सूचित होना चाहता हूँ',
          'Discover': 'खोज करना',
          'Filters': 'फिल्टर',
          'Distance': 'दूरी',
          'Today': 'आज',
          'Yesterday': 'कल',
          'Confirm': 'पुष्टि करना',
          'This is a list of people who have liked you and your matches.':
              'यह उन लोगों की सूची है जिन्होंने आपको और आपके मेलों को पसंद किया है।',
          'Age': 'आयु',
          'Interested in': 'इसमें दिलचस्पी है',
          'Sort by': 'इसके अनुसार क्रमबद्ध करें',
          'Match Sort': 'मिलान क्रमबद्ध करें',
          'Name': 'नाम',
          'Date & Time': 'दतिथि और समय',
          'Ascending': 'आरोही',
          'Descending': 'अवरोही',
          'My Basics': 'मेरी मूल बातें',
          'My Work & Education': 'मेरा काम और शिक्षा',
          'Height': 'ऊंचाई',
          'Ethnicity': 'जातीयता',
          'Religion': 'धर्म',
          'Exercise': 'व्यायाम',
          'Smoking': 'धूम्रपान',
          'Drinking': 'पीने',
          'Kids': 'बच्चे',
          'Star sign': 'राशि',
          'Core values': 'बुनियादी मूल्य',
          'Edit Basic Info': 'बुनियादी जानकारी संपादित करें',
          'I am': 'मैं हूँ',
          'My religion is': 'मेरा धर्म है',
          'Hindu': 'हिंदू',
          'Muslim': 'मुसलमान',
          'Sikh': 'सिख',
          'Other': 'अन्य',
          'Jewish': 'यहूदी',
          'Christian': 'ईसाई',
          'This is a list of people  who share a potential connection and a core connection':
              'यह उन लोगों की सूची है जो एक संभावित कनेक्शन और एक मुख्य कनेक्शन साझा करते हैं',
          'Select date of birth': 'जन्मतिथि चुनें',
          'My Deep Qualities': 'मेरे गहन गुण',
          "View Event":"View Event"

        },
        'el_GR': {
          'SelectTables': 'Επιλέξτε τραπέζια',
          'StoreSlug': 'Όνομα καταστήματος',
          'StoreTitle': 'Τίτλος καταστήματος',
          'Name': 'Ονομα',
          'logout': 'Είστε βέβαιοι ότι θέλετε να αποσυνδεθείτε?',
          'Notifications': 'Ειδοποιήσεις',
          'Clear': 'Εκκαθάριση',
          'No': 'Οχι',
          'Yes': 'Ναι',
          'SessionExpire': 'Η συνεδρία λήγει, συνδεθείτε ξανά',
          'NoInternet': 'Δεν υπάρχει σύνδεση στο διαδίκτυο',
          'Update': 'Ενημέρωση',
          "SomeThing": 'Κάτι δεν πήγε καλά. Παρακαλώ ξαναπροσπαθήστε',
          'PleaseWait': 'Παρακαλώ περιμένετε',
          'Success': 'Επιτυχία',
          'NotificationClear': 'Η ειδοποίηση διαγράφηκε με επιτυχία',
          'This is a list of people  who share a potential connection and a core connection':
              'Αυτή είναι μια λίστα ατόμων που μοιράζονται μια πιθανή σύνδεση και μια βασική σύνδεση',
          'Select date of birth': 'Επιλέξτε ημερομηνία γέννησης',
          'My Deep Qualities': 'Οι βαθιές μου ιδιότητες',

        },
        'fr_FR': {
          'SelectTables': 'Select Tables',
          'StoreSlug': 'Store Slug',
          'StoreTitle': 'Store Title',
          'Name': 'Name',
          'logout': 'Are you sure you want to logout?',
          'Notifications': 'Notifications',
          'Clear': 'Clear',
          'No': 'No',
          'Yes': 'Yes',
          'SessionExpire': 'Session expire please login again',
          'NoInternet': 'No Internet Connection',
          'Update': 'Update',
          "SomeThing": 'Something went wrong, please try again',
          'PleaseWait': 'Please wait',
          'Success': 'Success',
          'NotificationClear': 'Notification cleared successfully',
          'This is a list of people  who share a potential connection and a core connection':
              'Ceci est une liste de personnes qui partagent une connexion potentielle et une connexion principale',
          'Select date of birth': 'Sélectionnez la date de naissance',
          'My Deep Qualities': 'Mes qualités profondes',
        },
      };
}
